Computin/Computin/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('producto.urls')), # index = pagina de barra de busqueda del navegador
]

urlpatterns+= static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
    path('carrito/',include('carrito.urls')),
    path('ordenes/', include('ordenes.urls')),
    path('social-auth/', include('social_django.urls', namespace="social")),

]

Computin/carrito/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.decorators import login_required

app_name="carrito"

urlpatterns = [
    path('agregar_producto/<int:producto_id>', login_required(agregar_producto, login_url='/accounts/login') , name="agregar_producto"),
    path('eliminar_producto/<int:producto_id>', eliminar_producto, name="eliminar_producto"),
    path('disminuir_producto/<int:producto_id>', disminuir_producto, name="disminuir_producto"),
    path('Limpiar/', limpiar_carrito, name="limpiar_carrito"),




]

Computin/producto/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('', views.index, name='index'),
    path('nosotros', views.nosotros, name='nosotros'),
    path('ofertas', views.ofertas, name='ofertas'),
    path('productofiltrado/<int:num>', views.productosfiltrado, name='productos-filtrado'),
    path('Comprado/', views.CompraEnd, name='CompraEnd'),
    path('productos/', views.ProductosListView.as_view(), name='productos'),
    path('producto/<int:pk>', views.ProductoDetailView.as_view(), name='producto-detail'),
    path('login/', auth_views.LoginView.as_view(template_name='registration/login.html') , name='login'),
    path('registro/', views.registro , name="registro"),
    path('agregarprod/', views.ProductoCreate.as_view(),name="agregarprod"),
    path('modificar/<int:pk>', views.ProcutoUpdate.as_view(),name="modificar"),
    path('producto_admin/',views.productoadmin,name='producto_admin'),
    path('eliminarprod/<int:pk>',views.ProductoDelete.as_view(),name='eliminarprod'),
    path('buscar/', views.buscar, name="buscar"),


]

Computin/producto/models.py
from django.db import models
from django.urls import reverse # Se utiliza para direccionar los path de nmuestro proyecto asociado al modelo
import uuid # Se utiliza para relacionar objetos de de Instancia de productos


# Create your models here.
class Producto(models.Model):
	idProd = models.IntegerField(primary_key=True,help_text='Id única del producto')
	NombreProd = models.CharField(max_length=150)
	MarcaProd = models.CharField(max_length=150)
	CategoriaProd = models.CharField(max_length=150,null=True)
	CategoriaEsp = models.CharField(max_length=150,null=True,help_text='Categorias especiales (Destacados,Ofertas,Populares).Sino posee dejar como "Ninguno"')
	PrecioProd = models.IntegerField(null=True)
	StockProd = models.IntegerField(null=True)
	imageProd = models.ImageField(upload_to='imagesProd/', null=True, blank=True)
	DescripciónProd = models.TextField(max_length=5000)

	def __str__(self):
		return self.NombreProd

	def get_absolute_url(self):
		return reverse('producto-detail', args=[int(self.idProd)])

Computin/producto/forms.py
from django import forms

from . models import Producto

class ProductoForms(forms.ModelForm):

    idProd = forms.CharField(label='id',max_length=150,widget=forms.TextInput(attrs={'class':'form-control'}))
    NombreProd = forms.CharField(label='Nombre Producto',max_length=150,widget=forms.TextInput(attrs={'class':'form-control'}))
    MarcaProd = forms.CharField(label='Marca',max_length=150,widget=forms.TextInput(attrs={'class':'form-control'}))
    CategoriaProd = forms.CharField(label='Categoria Producto',max_length=150,widget=forms.TextInput(attrs={'class':'form-control'}))
    CategoriaEsp = forms.CharField(label='Categoria Especial',max_length=150,widget=forms.TextInput(attrs={'class':'form-control'}))
    PrecioProd = forms.CharField(label='Precio',max_length=150,widget=forms.TextInput(attrs={'class':'form-control'}))
    StockProd = forms.CharField(label='Precio',max_length=150,widget=forms.TextInput(attrs={'class':'form-control'}))
    DescripcionProd = forms.CharField(label='descripción',max_length=150,widget=forms.TextInput(attrs={'class':'form-control'}))

    class Meta:
        model = Producto
        fields = ('idProd','NombreProd', 'MarcaProd', 'CategoriaProd','CategoriaEsp','PrecioProd','StockProd','DescripcionProd')

Computin/producto/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponseRedirect
from . models import Producto
from django.views import generic
from django import forms
from carrito.carrito import Carrito
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate,login
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    num_Productos = Producto.objects.all().count()
    num_Prod_Disp = Producto.objects.all().count()
    num_Prod = Producto.objects.all()
    DestacadoProd = Producto.objects.all().filter(CategoriaEsp__icontains = 'Destacados') #icontains sirve para buscar entre mayus y minus
    OfertaProd = Producto.objects.all().filter(CategoriaEsp__icontains = 'Ofertas')
    PopularProd = Producto.objects.all().filter(CategoriaEsp__icontains = 'Populares')
    num_visitas=request.session.get('num_visitas',0)
    num_visitas=request.session['num_visitas']=num_visitas+1
    carrito = Carrito(request)

    return render(
        request,
        'index.html',
        context={'num_Productos': num_Productos,'num_Prod_Disp': num_Prod_Disp, 'num_Prod' : num_Prod,
        'DestacadoProd' : DestacadoProd, 'OfertaProd' : OfertaProd, 'PopularProd' : PopularProd,'num_visitas':num_visitas}
    )

def nosotros(request):
    return render(request,'nosotros.html')

def CompraEnd(request):
    return render(
        request,
        'CompraEnd.html'
    )

def ofertas(request):
    DestacadoProd = Producto.objects.all().filter(CategoriaEsp__icontains = 'Destacados') #icontains sirve para buscar entre mayus y minus
    OfertaProd = Producto.objects.all().filter(CategoriaEsp__icontains = 'Ofertas')
    PopularProd = Producto.objects.all().filter(CategoriaEsp__icontains = 'Populares')
    return render(
        request,
        'ofertas.html',
        context= {'DestacadoProd' : DestacadoProd,
        'OfertaProd' : OfertaProd, 'PopularProd' : PopularProd},
    )

def registro(request):
    data = {
        'form':CustomUserCreationForm()
    }

    if request.method == 'POST':
        formulario = CustomUserCreationForm(data=request.POST)
        if formulario.is_valid():
            formulario.save()
            user = authenticate(username=formulario.cleaned_data["username"],password=formulario.cleaned_data["password1"])
            usernames=formulario.cleaned_data["username"]
            messages.success(request,f'Cuenta creada exitosamente, Bienvenid@s a Computin | Hola   {usernames}')
            login(request, user)
            return redirect(to="index")
        data["form"] = formulario
    return render(request,'registration/registro.html',data)

def productoadmin(request):
    todoprod = Producto.objects.all()
    return render(request,'producto/producto_admin.html',context={'todoprod':todoprod})

def productosfiltrado(request,num):

        cate = Producto.objects.all()
        num1 = num
        return render(request,'producto_filtrado.html',context={'cate':cate,'num1':num1})

def buscar(request):
    busqueda = request.GET.get('buscar')
    productos = Producto.objects.filter(NombreProd__contains=busqueda)
    return render(request, 'buscar.html', {'productos': productos})

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

class ProductoDetailView(generic.DetailView):
    model = Producto

class ProductosListView(generic.ListView):
    model = Producto


class ProductoCreate(CreateView):
    model = Producto
    fields = '__all__'

class ProcutoUpdate(UpdateView):
    model = Producto
    fields = '__all__'

class ProductoDelete(DeleteView):
    model = Producto
    success_url = reverse_lazy('index')


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username' ,'first_name','last_name',"email","password1","password2"]


class EmailChangeForm(forms.Form):
    error_messages = {
        'email_mismatch': "Error al confirmar el email, intente nuevamente",
        'not_changed': "¡El correo ingresado es igual al anterior, no se aplicaron cambios!",
    }

    new_email1 = forms.EmailField(
        label="Ingrese su nuevo correo",
        widget=forms.EmailInput,
    )

    new_email2 = forms.EmailField(
        label="Confirme su nuevo correo",
        widget=forms.EmailInput,
    )

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(EmailChangeForm, self).__init__(*args, **kwargs)

    def clean_new_email1(self):
        old_email = self.user.email
        new_email1 = self.cleaned_data.get('new_email1')
        if new_email1 and old_email:
            if new_email1 == old_email:
                raise forms.ValidationError(
                    self.error_messages['not_changed'],
                    code='not_changed',
                )
        return new_email1

    def clean_new_email2(self):
        new_email1 = self.cleaned_data.get('new_email1')
        new_email2 = self.cleaned_data.get('new_email2')
        if new_email1 and new_email2:
            if new_email1 != new_email2:
                raise forms.ValidationError(
                    self.error_messages['email_mismatch'],
                    code='email_mismatch',
                )
        return new_email2

    def save(self, commit=True):
        email = self.cleaned_data["new_email1"]
        self.user.email = email
        if commit:
            self.user.save()
        return self.user



def email_change(request):
    form = EmailChangeForm()
    if request.method=='POST':
        form = Email_Change_Form(User,request.POST)
        if form.is_valid():
            if request.user.is_authenticated:
                if form.cleaned_data['email1']  == form.cleaned_data['email2']:
                    user = request.user
                    u = User.objects.get(username=user)
                    # get the proper user
                    u.email = form.cleaned_data['email1']
                    u.save()
                    return HttpResponseRedirect("/accounts/login/")
    else:
        return render_to_response("email_change.html", {'form':form},
                                   context_instance=RequestContext(request))

Computin/producto/templates/producto/compra_form.html
{%extends "base_generic.html" %}

{% block title%}<title>ComPutin - Comprar</title>{% endblock %}


{%block content %}

<!-- FORMULARIO DE COMPRA -->
<div class="container-fluid" >
    <div class="row">                       
        <form class="col-md fondo_form_compra" action="" name="CrearCompra" method="POST">
            <hr>
            {%csrf_token%}
            <div class="alert alert-success " role="alert">
                <h1>Formulario de compra</h1>
            </div>                      
            <div class="row-sm-6"> 
                <label style="color: black; position: static; text-align: center;">Nombres y apellido</label>                              
                <div class="form-group row-sm-6">                    
                    <div>
                        {{form.nombre}}
                    </div>
                    
                </div>

                <label style="color: black; position: static; text-align: center;">Correo</label>
                <div class="form-group row-sm-6">                    
                    <div>
                        {{form.correo}}
                    </div>                    
                </div>
                <label style="color: black; position: static; text-align: center;">Número de teléfono</label>
                <div class="form-group row-sm-6">                    
                    <div>
                        {{form.numTelefonico}}
                    </div> 
                    
                </div>
                <label style="color: black; position: static; text-align: center;">Comuna</label>
                <div class="form-group col-md">                    
                    <div>
                        {{form.comuna}}
                    </div>                    
                </div>
                <label style="color: black; position: static; text-align: center;">Dirección</label>
                <div class="form-group col-md">                    
                    <div>
                        {{form.direccion}}
                    </div> 
                    
                </div>
                <label style="color: black; position: static; text-align: center;">ID Producto</label>
                <div class="form-group col-md">                    
                    {% if idprod != 0 %}
                    <div>
                        {{form.idProducto}}
                    </div>                     
                    {% else %}
                    <div>
                        {{form.idProducto}}
                    </div>
                    {% endif %}
                </div>
                <label style="color: black; position: static; text-align: center;">Comentario</label>
                <div class="form- col-md">                    
                    <div>
                        {{form.comentario}}
                    </div>                    
                </div>                        
                <div class="form-group col-md">
                    <hr>
                    <input class="btn btn-primary" type="submit"  value="Enviar">
                    <hr>
                </div>
                <div class="alert alert-info" role="alert">
                    Para ventas telefónicas o información sobre stock de productos llamar al: +56991349101
                </div>
                <hr>
                <div style="visibility: hidden;">
                    {{form.idCompra}}
                </div> 
            </div>
            
        </form>
        
    </div>
    
</div>

{%endblock%}

Computin/producto/templates/producto/producto_admin.html
{% extends "base_generic.html" %}

{% block title%}<title>ComPutin - Administrar productos</title>{% endblock %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-sm" style="background-color: ghostwhite;border-radius: 2px;">
      <div class="container-fluid p-1 my-1 text-black" style="background-color: transparent; border-radius: 20px; text-align:left;">
        <strong><h1>Listado de productos</h1></strong>
        <hr>
      </div>

    {% if user.username == "computin" %}
      <div class="conteiner">
        <div class="row cards_productos" style="margin-left: 6%;margin-right: 6%;">
          {% for producto in todoprod %}
          <div class="col-md tamañoCartas" style="max-width: 234px;">
            <div class="card text-center border-secondary bg-light" >
              <div class="card-body">
                  <p class="card-title">{{ producto.NombreProd }}</p>
                  <img class="imagendecard" src="{{ producto.imageProd.url}}" alt="producto">
                  <div class="card-footer bg-light">
                      <div class="shadow-lg w-10 p-1 bg-light rounded">
                          <div class="alert alert-primary">
                              ${{ producto.PrecioProd }}
                          </div>
                          <a href="{% url "eliminarprod" producto.idProd %}" class="btn btn-primary" ><i class="far fa-trash-alt"></i></a>
                          <a href="{% url "modificar" producto.idProd %}" class="btn btn-success" ><i class="far fa-edit"></i></a>

                      </div>

                  </div>
              </div>
          </div>
          </div>
          {% endfor %}
        </div>
      </div>
    {% endif %}

    </div>
  </div>
</div>



{% endblock %}

Computin/producto/templates/producto/producto_confirm_delete.html
{% extends "base_generic.html" %}

{% block title%}<title>ComPutin - Eliminar producto</title>{% endblock %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-sm" style="background-color: ghostwhite;border-radius: 2px;">
      <div class="container-fluid p-1 my-1 text-black" style="background-color: transparent; border-radius: 20px; text-align:center;">
        {% if user.username == "computin" %}
            <div class="col-md">
                <div class="card text-center border-secondary bg-light">
                    <div class="card-body">
                        <a href="{{ producto.get_absolute_url }}">
                        <p class="card-title">{{ producto.NombreProd }}</p></a>
                        <a href="{{ producto.get_absolute_url }}"><img class="imagendecard" src="{{ producto.imageProd.url}}" alt="producto"></a>
                        <div class="card-footer bg-light">
                            <div>
                                <div class="alert alert-primary">
                                    ${{ producto.PrecioProd }}
                                </div>
                                <a href="{{ producto.get_absolute_url }}" class="btn btn-success" ><i class="far fa-eye"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <form action="" method="POST">
            {% csrf_token %}
		<br>
		<br>
		<br>
		<br>
            <input type="submit" class="btn btn-danger"value="Si,Eliminar">
            <a href="https://pipatzo.pythonanywhere.com/producto_admin/" class="btn btn-primary">Volver</a>
        </form>
        {% else %}
        <div>
            <h1>No tienes permisos para acceder a este contenido.</h1>
        </div>
        {% endif %}
      </div>
    </div>
  </div>
</div>

{% endblock %}

Computin/producto/templates/producto/producto_detail.html
{% extends "base_generic.html" %}

{% block title%}<title>ComPutin - {{ producto.NombreProd }}</title>{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm" style="background-color: ghostwhite;">
            <div class="container-fluid p-1 my-1 text-black" style="background-color: transparent; border-radius: 20px; text-align:left;">
                <h5>Incio>Productos>{{producto.CategoriaProd}}>{{ producto.NombreProd }} </h5>
            </div>

            <div >
                <div class="container">
                    <div class="row">
                        <div class="align-self-center col-sm-4">
                            <img class="img imagen_prod " src="{{ producto.imageProd.url}}"  alt="productos" >
                        </div>
                        <div class="col-sm-8">
                            <div class="jumbotron cuadro_venta " style="float: right;text-align:center;">
                                <h1>{{ producto.NombreProd }}</h1>
                                <p>ID: {{ producto.idProd }}</p>
                                <hr>
                                <br>
                                <h2>$ {{ producto.PrecioProd }}</h2>
                                <br>
                                {% if producto.StockProd == 0 %}
                                <p style="color:red">Stock disponible: {{producto.StockProd}}</p>
                                <p style="color:red">Despacho a domicilio: No</p>
                                <br>
                                <div class="alert alert-danger" role="alert">
                                    ¡Aviso, producto sin stock!
                                </div>


                                {% endif %}

                                {% if producto.StockProd < 5 and producto.StockProd > 0 %}
                                <p style="color:steelblue">Stock disponible: {{producto.StockProd}}</p>
                                <p style="color:steelblue">Despacho a domicilio: Si</p>
                                <div class="alert alert-warning" role="alert">
                                Stock bajo, Comuniquese con la tienda antes de hacer el pago de este producto
                                </div>
                                <a href="{% url 'carrito:agregar_producto' producto.idProd %}" class="btn btn-success"><i class="fas fa-cart-plus" style="margin: 0%;"></i> Agregar</a>
                                {% endif %}

                                {% if producto.StockProd >= 5 %}
                                <p style="color:green">Stock disponible: {{producto.StockProd}}</p>
                                <p style="color:green">Despacho a domicilio: Si</p>
                                <a href="{% url 'carrito:agregar_producto' producto.idProd %}" class="btn btn-success"><i class="fas fa-cart-plus" style="margin: 0%;"></i> Agregar</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 " style="text-align: justy;">
                            <pre style="font-family: Arial, Helvetica, sans-serif;
                            white-space: pre-wrap;
                            white-space: -moz-pre-wrap;
                            white-space: -pre-wrap;
                            white-space: -o-pre-wrap;
                            word-wrap: break-word;" >{{ producto.DescripciónProd }}</pre>
                        </div>
                    </div>
                    <hr>
                    <div class="col-sm-9" style="margin-left: 15%;">
                        {% load static %}
                        <img class="border-secundary w-100" src="{% static 'img/banner-envios.jpg' %}">
                    </div>
                    <hr>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

Computin/producto/templates/producto/producto_form.html
{% extends "base_generic.html" %}

{% block title%}<title>ComPutin - Agregar Producto</title>{% endblock %}

{% block content %}
    {% if user.username == "computin" %}
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="container" style="background-color: ghostwhite; margin-top: 0%; height: 120%;">
                    <div class="titulo-prin">
                        <h2>Administración Producto</h2>
                    </div>
                    <div class="form-top-left">
                        <div class="titulos-p">
                            <h2 for="">ID: </h2>
                         </div>
                        <div class="cajaTexto">
                            {{ form.idProd }}
                         </div>
                        <div class="titulos-p">
                            <h2 for="">Nombre Producto: </h2>
                         </div>
                        <div class="cajaTexto">
                            {{ form.NombreProd }}
                         </div>
                        <div class="titulos-p">
                            <h2 for="">Marca: </h2>
                         </div>
                        <div class="cajaTexto">
                            {{ form.MarcaProd }}
                         </div>
                        <div class="titulos-p-cat">
                            <h2 >tarjeta - almacenamiento - perifericos - componente pc - equipos armados </h2>
                        </div>
                        <div class="titulos-p">
                            <h2 for="">Categoria Producto: </h2>
                         </div>
                        <div class="cajaTexto">
                            {{ form.CategoriaProd }}
                         </div>
                        <div class="titulos-p-cat">
                            <h2 >Destacados - Ofertas - Populares - Ninguno</h2>
                        </div>
                        <div class="titulos-p">
                           <h2 for="">Categoria Especial: </h2>
                         </div>
                        <div class="cajaTexto">
                            {{ form.CategoriaEsp }}
                         </div>
                        <div class="titulos-p">
                         <h2 for="">Precio: </h2>
                         </div>
                        <div class="cajaTexto">
                         {{ form.PrecioProd }}
                         </div>
                        <div class="titulos-p">
                         <h2 for="">Stock: </h2>
                         </div>
                        <div class="cajaTexto">
                         {{ form.StockProd }}
                         </div>
                    </div>
                    <div class="form-bottom-rigth">
                        <div class="img-pro">
                            <div class="cajai">
                                {{ form.imageProd }}
                            </div>
                       </div>
                       <div class="des-pro" >
                            <div class="titulos-p">
                                <h2>Descripcion: </h2>
                            </div>
                            <div class="cajaTexto" >
                                {{ form.DescripciónProd }}
                            </div>
                       </div>
                    </div>
                   <div class="cajabtn">
                       <input type="submit"  class="btn btn-warning" value="Guardar">
                   </div>
                </div>
        </form>
    {% else %}
        <div class="container p-5 my-5 border" style="background-color: ghostwhite; margin-top: 20%; height: 120%;">
            <h1>No tienes permisos para acceder a este contenido.</h1>
        </div>
    {% endif %}
{% endblock %}

Computin/producto/templates/producto/producto_list.html
{% extends "base_generic.html" %}

{% block title%}<title>ComPutin - Productos</title>{% endblock %}

{% block content %}



<div class="container">
  <div class="row">
    <div class="col-sm" style="background-color: ghostwhite;border-radius: 2px;">
      <div class="container-fluid p-1 my-1 text-black" style="background-color: transparent; border-radius: 20px; text-align:left;">
        <strong><h1>Listado de productos</h1></strong>
        <hr>
      </div>

    {% if producto_list %}
        <div class="container-fluid">
            <div class="row cards_productos" style="margin-left: 6%;margin-right: 6%;max-width: 100%;">

            {% for producto in producto_list %}
                <div class="col-md tamañoCartas" style="max-width: 100%;">
                    <div class="card text-center border-secondary bg-light" >
                        <div class="card-body">
                        <a href="{{ producto.get_absolute_url }}"><p class="card-title">{{ producto.NombreProd }}</p></a>
                        <a href="{{ producto.get_absolute_url }}"><img class="imagendecard" src="{{ producto.imageProd.url}}" alt="producto"></a>
                            <div class="card-footer bg-light">
                                <div>
                                    <div class="alert alert-primary">
                                    ${{ producto.PrecioProd }}
                                    </div>
                                {% if producto.StockProd == 0 %}
                                <a href="#" class="btn btn-danger" ><i class="fas fa-exclamation-triangle" style="margin: 0%;"></i></a>
                                {% else %}
                                <a href="{% url 'carrito:agregar_producto' producto.idProd %}" class="btn btn-primary" ><i class="fas fa-cart-plus" style="margin: 0%;"></i></a>
                                {% endif %}
                                <a href="{{ producto.get_absolute_url }}" class="btn btn-success" ><i class="far fa-eye"></i></a>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <hr>
        </div>
      {% endif %}

    </div>
  </div>
</div>




{% endblock %}